### ISSUE TITLE
Code generation in the WordPress plugin (Beta 1.2)

### ISSUE THREAD

**Issue by ElGringo** [highcharts/highcharts-editor#112]
Hello,
the preview seems to be is generated dynamically. So things like tooltip and hovers work fine there.  The finally generated code (after "Close  & generate chart") on the other hand is pure html. Therefore some dynamic features don't work and it is nearly impossible to later modify the code by hand. 

Is this by design or am I doing something wrong? 

Thank you and best regards

Rico

**Comment by cvasseng** [comment]
Hi Rico,

the chart will always be static when viewed in the Wordpress editor, but should be interactive once you publish the post (or preview it). Are you getting static charts in published/preview'ed pages also?

Chris

**Comment by ElGringo** [comment]
Hello Chris,

exactly. The previewed and published code seems static. It starts with
`<div id="highcharts-3640ab61-de28-4fed-b8f8-2c0f21b3197c"><svg xmln ... </svf></div>`
and is followed by some JavaScript 
`<script>
(function(){ function include(script, next) {var sc=document.createElement("script") ...`

I think the only change I did to the original Beta 1.2 prebuild is to activate the advanced editor by adding 
`wp_enqueue_script("highcharts-editor-advanced",  plugin_dir_url(__FILE__) . "highcharts-editor.advanced.min.js");`
in the file `highcharts-editor.wordpress.0.1.2/highcharts-editor.php`

Maybe that is was what caused the problems. I will try the vanilla one next.

Best regards

Rico

**Comment by cvasseng** [comment]
Are you getting any errors in the dev console?

**Comment by cvasseng** [comment]
I've found a way to trigger it, you can expect a fix shortly.

**Comment by cvasseng** [comment]
Looks like the issue is was that WP occasionally quotes special characters inside the injected `<script>` tag. 

ac90ec7 fixes this. A new prebuilt release will be prepared later this week (I have some other fixes I want to include too). In the meantime, you can build it yourself by cloning the repository and running `npm install && gulp` in the project folder. This will produce the WP plugin in the `dist/bundles/` folder.

Please let me know if this fixes the issue for you. In any case I'm leaving this open as a reference for others that may have the same issue before I bake the new release.

**Comment by ElGringo** [comment]
Can't thank you enough. It works great!
