### ISSUE TITLE
Thousandssep not saving, or not returning after loading

### ISSUE THREAD

**Issue by phoenixrip** [highcharts/highcharts-editor#117]
wanting to have a ',' as a thousands separator;
Although a little weird, I managed to get one to display by putting 'space ,' into the thousandsep lang option and using the point format {point.y:,.0f}

However if you save and reload the project the , is gone, replaced by a default space, and although the ' ,'  is in the thousandssep option still, you have to retype it to get it to display on the chart again.

So sorry to bombard you with a load of issues; this is a wonderfully powerful tool and I hope flagging up things is useful :)

**Comment by cvasseng** [comment]
Looks like it was an issue with order of operations along with not loading global options properly when loading projects.

Fixed in the two referenced commits. There's a new release coming up later this week with the latest fixes, until then you can build your own version by cloning the repo and running `npm install && gulp` in the root folder, which produces distribution files in the `dist/` folder.

And don't feel bad for submitting issues, It's very helpful! :)

Thanks
