### ISSUE TITLE
There is a hidden JSON tab in import, how do I turn it on?

### ISSUE THREAD

**Issue by pdnorcross** [highcharts/highcharts-editor#125]
Why is it hidden?
If I need another file to activate where is that?

Also jquery-simple-rest doesn't seem to work.
Loads the file but Can't get it to appear. Documentation does not help. Really should provide a full example with this. How come is it listed as an example, but isn't tied to the repository straight up.

**Comment by cvasseng** [comment]
The JSON import tab was disabled because it was causing a lot of confusion as to what kind of data was supposed to go into it. The project save/load functionality largely replaced it. It can't be enabled without changing the code (line 140 in `src/ui/highed.dataimporter.js`).

The jQuery-simple-rest plugin does not have a UI - it's an [editor plugin](https://github.com/highcharts/highcharts-editor/wiki/Plugins), which is just executed when the chart changes. That group of plugins are meant for things like auto-saving. 

It's initialized by adding 
    {
        "plugins": {
             "jquery-simple-rest": {
                //options here, e.g. "url": "..."
             }  
        }
    }

to the editor, after including the plugin script into your page.

Note sure what you mean by 
> If I need another file to activate where is that? 

Please clarify, and I'll do my best to answer.

**Comment by ualr-djspillers** [comment]
@cvasseng What might clarify this is that we are trying to use the WordPress integration with the ModalEditor and want to build charts that use jquery rest calls for live data.

What we've done so far in the WordPress plugin is:

1. Modified highcharts-editor.php to enqueue the jquery-simple-rest.js script after the highcharts-editor.min.js script
2. Modified editor_plugin.js (the TinyMCE plugin) to include the config you specify above to the highed.ModalEditor object, like this:
```
var modal = highed.ModalEditor(false, {
                    features: 'import templates customize welcome done',
                    plugins: {
                         "jquery-simple-rest": {

                         }
                    },
                    allowDone: true
                }, function (chart) {
                   var html = chart.export.html(true);
                   editor.insertContent('<div class="mceNonEditable">' + html + '</div><p></p>');
                })
    ;
```
I see the following error in the JS console when displaying the editor inside a WordPress page:

`Uncaught TypeError: highed.plugins.use is not a function`

**Comment by cvasseng** [comment]
If you're trying to produce charts with live data after insertion into posts, this will not work. Editor plugins are for auto-saving in the editor itself; they will not be part of the output.

There is currently no plugin layer that allows for that kind of integrations. It's on the roadmap, but the ETA is currently unknown (likely some time in Q2/Q3). 

As it stands, the only way to do live data is to either modify the editor heavily yourself, or by inserting a callback manually in the chart constructor in the editor output to do the jQuery call.
