### ISSUE TITLE
Client Side Events on Toolbar

### ISSUE THREAD

**Issue by suhashankare** [highcharts/highcharts-editor#159]
HI,

I want to attach client side events on the Save button to store chart in component node and Open button event to access stored chart properties from any node, so help me out with this scope and  how do i achieve such logic with the help of "Highed"

Thank you 
_-SuHas_

**Comment by cvasseng** [comment]
Hi, this is not possible to do out of the box. The closest you'll get is to add your own icons using:
 
```
editor.toolbar.addIcon({
   icon: 'fa-floppy-o',
   click: function () {
        // Do stuff with result of editor.chart.toProject()
    }
});
```

Also, we try to keep the issue tracker to actual bugs rather than general user questions. Please use the issue template, and if you have user questions in the future, please use one of our support channels at: https://www.highcharts.com/support
