### ISSUE TITLE
The doDone function couldn't be able to export json

### ISSUE THREAD

**Issue by popoycol** [highcharts/highcharts-editor#84]
I think the function should be that.
![image](https://cloud.githubusercontent.com/assets/4425141/20886526/5f5c3aa8-bb31-11e6-9416-1096429c8621.png)

**Comment by cvasseng** [comment]
Hi, thanks for submitting an issue on this.

I actually want to have it pass a ChartPreview instance only, so that the callback could do the conversion to the desired format by calling `chart.export.html(..)`, `chart.export.json(..)`, `chart.export.svg(..)`, and `chart.export.js(..)`. I think this would be the cleanest and most flexible.

Would this change cover your use case?

**Comment by popoycol** [comment]
Thank you for your answer.
You mean that
![image](https://cloud.githubusercontent.com/assets/4425141/20925198/65bca74c-bbf0-11e6-8c15-8acdac441e0a.png)

**Comment by cvasseng** [comment]
function doDone() {
        if (highed.isFn(fn)) {
            fn(editor.chart);
        }
    }

As it may be useful to have the full chart instance in the callback.

**Comment by popoycol** [comment]
That's great. Thank you.
