### ISSUE TITLE
Import Json Issue

### ISSUE THREAD

**Issue by popoycol** [highcharts/highcharts-editor#85]
when i import one json like this.
![image](https://cloud.githubusercontent.com/assets/4425141/20886645/0f4a3c26-bb32-11e6-9158-b3e379bf26a0.png)
I got the graphics on the right.

But when i import a json like this.
![image](https://cloud.githubusercontent.com/assets/4425141/20886768/900f919e-bb32-11e6-8547-1a77d664868e.png)
Then i change the template , i got the error image like this.
![image](https://cloud.githubusercontent.com/assets/4425141/20886815/d32f3f10-bb32-11e6-9329-5f3b09ffafbd.png)

I think the loadJSONData function needs to be changed, like it should look like the following, or a better method.
![image](https://cloud.githubusercontent.com/assets/4425141/20887127/58ff0c50-bb34-11e6-9064-88c4953d65d8.png)

**Comment by cvasseng** [comment]
Thanks for reporting. 

A patch is upcoming.

**Comment by popoycol** [comment]
Thanks.

**Comment by cvasseng** [comment]
Commit 1b8920373116e53f07785ea588c2516a0ca2e01a fixes project loading/saving. 

Note that this only works when using the gear menu to load and save the project. This is because once something is exported as JSON, the template options are combined with the manually customized options in order to reproduce the chart by calling the chart constructor. 

The above mentioned commit stores the template state and manually modified options separately, so that the state is properly maintained between a save and a load. This also allows the project json file to be expanded in the future to contain additional editor-specific meta settings.
